package mx.gob.inr.utils;

public interface ConstantesHojaEnfermeria {
	
	  int SIN_SELECCION = -1;
	
	  int H_INICIO_MATUTINO = 8;
	  int H_INICIO_VESPERTINO = 15;
	  int H_INICIO_NOCTURNO = 1;
	  int H_FIN_MATUTINO = 14;
	  int H_FIN_VESPERTINO = 20;
	  int H_FIN_NOCTURNO = 24;
	
	
	  short S_VALORACION = 1;
	  short S_DIAGNOSTICOS_INTERVENCIONES = 2;
	  short S_INDICADORES_CALIDAD = 3;
	
	
	  short R_PROMOCION_NORMALIDAD =8;
	  short R_INGRESOS =13;
	  short R_MEDICAMENTOS =18;
	  short R_ESCALAGLASGOW_OTROS =95;
	  
	  
	  
	  short R_TEMPERATURA =10;
	  short R_FRECUENCIA_CARDIACA =11;
	  short R_TENSION_ARTERIAL_DIASTOLICA =12;
	  short R_TENSION_ARTERIAL_SISTOLICA =17;
	  short R_FRECUENCIA_RESPIRATORIA =78;
	  short R_LABORATORIO_GABINETE =85;
	  short R_ESCALA_DOLOR =15;
	  short R_DIETA =16;
	  short R_EGRESOS =14;
	  short R_VENOCLISIS_INSTALADA =65;
	  short R_PREVENSION_CAIDAS =66;
	  short R_SONDA_VESICAL_INSTALADA =67;
	  short R_PREVENSION_ULCERA_PRESION =68;
	  short R_INTERVENCIONES_ACCESO_VENOSO =69;
	  short R_REQUISITOS =79;
	  short R_DIAGNOSTICO_ENFERMERIA =83;
	  short R_OBSERVACIONES =84;
	  short R_OTROS_DATOS =86;
	  short R_FALTANTEPASAR = 93;
	  short R_ESCALAMADDOX = 94;
	
	
	  int  P_DIETA_DIETA =426;
	  int  P_DIETA_MATUTINO =116;
	  int  P_DIETA_VESPERTINO =117;
	  int  P_DIETA_NOCTURNO =118;
	  int  P_DESARROLLO =417;
	  int  P_DESVIACION_SALUD =418;
	  
	  int  P_FECHA_INSTALACION_V =427;
	  int  P_DIAS_V =428;
	  int  P_CALIBRE_V =534;
	  
	  int  P_FECHA_INSTALACION_S =429;
	  int  P_DIAS_S =430;
	  int  P_MATERIAL_S =431;
	  int  P_CALIBRE_S =432;
	  int  P_GLOBO_S =433;
	  
	  int  P_DIAGNOSTICO_MATUTINO =419;
	  int  P_DIAGNOSTICO_VESPERTINO =420;
	  int  P_DIAGNOSTICO_NOCTURNO =421;
	  int  P_OBSERVACIONES_MATUTINO =422;
	  int  P_OBSERVACIONES_VESPERTINO =423;
	  int  P_OBSERVACIONES_NOCTURNO =424;
	  
	  
	  int P_TEMEPRATURA =7;
	  int P_FRECUENCIA_CARDIACA =8;
	  int P_TENSION_ARTERIAL_DIASTOLICA =9;
	  int P_TENSION_ARTERIAL_SISTOLICA =10;
	  int P_FRECUENCIA_RESPIRATORIA =416;
	  int P_LABORATORIO_GABINETE =425;
	  
	  int  P_FALTANTE_PASAR_MATUTINO =476;
	  int  P_FALTANTE_PASAR_VESPERTINO =477;
	  int  P_FALTANTE_PASAR_NOCTURNO =478;
	  
	  
	  int  P_ESCALA_MADDOX_MATUTINO =479;
	  int  P_ESCALA_MADDOX_VESPERTINO =480;
	  int  P_ESCALA_MADDOX_NOCTURNO =481;
	  
	  int  P_ESCALA_MADDOX_GENERICO = 355;
	  
	  int P_REQUESITO_DESARROLLO = 417;
	  int P_REQUESITO_DESVIACION = 418;
	  
	  int P_RELIGION = 452;

}
